export default [
  {
    id: 1,
    user_id: 1,
    destination: "Paris, France",
    trip_purpose: "leisure",
    activities: "Dining/Going Out, Sightseeing, Shopping",
    trip_name: "Fashion week in France",
    isPublic: true,
    isSaved: false,
  },
  {
    id: 2,
    user_id: 1,
    destination: "Tokyo, Japan",
    trip_purpose: "Business",
    activities: "Networking events, Tech conference",
    trip_name: "Japan Adventure",
    isPublic: true,
    isSaved: false,
  },
  {
    id: 3,
    user_id: 2,
    destination: "Crato, Portugal",
    trip_purpose: "leisure",
    activities: "Camping, Music Festival",
    trip_name: "Waking Life Festival",
    isPublic: true,
    isSaved: false,
  },
  {
    id: 4,
    user_id: 2,
    destination: "Rome, Italy",
    trip_purpose: "leisure",
    activities: "Sightseeing, Dining/Going Out",
    trip_name: "Holidays in Rome",
    isPublic: true,
    isSaved: false,
  },
  {
    id: 5,
    user_id: 3,
    destination: "Sydney, Australia",
    trip_purpose: "leisure",
    activities: "Water Sports, Hiking ",
    trip_name: "Surf trip in Sydney",
    isPublic: true,
    isSaved: false,
  },
  {
    id: 6,
    user_id: 1,
    destination: "Bora Bora, French Polynesia",
    trip_purpose: "leisure",
    activities: "Snorkeling, Private Dinners",
    trip_name: "Romantic Escape in Bora Bora",
    isPublic: true,
    isSaved: false,
  },
  {
    id: 7,
    user_id: 1,
    destination: "Santorini, Greece",
    trip_purpose: "leisure",
    activities: "Wine Tasting, Sunset Cruises",
    trip_name: "Aegean Bliss in Santorini",
    isPublic: true,
    isSaved: false,
  },
  {
    id: 8,
    user_id: 1,
    destination: "Machu Picchu, Peru",
    trip_purpose: "leisure",
    activities: "Hiking, Cultural Exploration, Photography",
    trip_name: "Lost City of the Incas",
    isPublic: false,
    isSaved: true,
  },
  {
    id: 9,
    user_id: 1,
    destination: "Maldives",
    trip_purpose: "leisure",
    activities: "Scuba Diving, Spa Retreats",
    trip_name: "Luxury Retreat in the Maldives",
    isPublic: true,
    isSaved: false,
  },
  {
    id: 10,
    user_id: 1,
    destination: "Petra, Jordan",
    trip_purpose: "leisure",
    activities: "Historical Tours, Desert Camping",
    trip_name: "Exploring the Rose City",
    isPublic: false,
    isSaved: true,
  },
];
