export default [
  {
    id: 1,
    user_id: 1,
    destination: "Paris, France",
    trip_purpose: "leisure",
    activities: "Dining and going out Sightseeing Shopping",
    trip_name: "Fashion week in France",
    isPublic: true,
    isSaved: false,
  },
  {
    id: 2,
    user_id: 1,
    destination: "Tokyo, Japan",
    trip_purpose: "Business",
    activities: "Networking events, Tech conference",
    trip_name: "Japan Adventure",
    isPublic: true,
    isSaved: false,
  },
  {
    id: 3,
    user_id: 2,
    destination: "Crato, Portugal",
    trip_purpose: "leisure",
    activities: "Camping, Music Festival",
    trip_name: "Waking Life Festival",
    isPublic: true,
    isSaved: false,
  },
  {
    id: 4,
    user_id: 2,
    destination: "Rome, Italy",
    trip_purpose: "leisure",
    activities: "Sightseeing, Dining and going out",
    trip_name: "Holidays in Rome",
    isPublic: true,
    isSaved: false,
  },
  {
    id: 5,
    user_id: 3,
    destination: "Sydney, Australia",
    trip_purpose: "leisure",
    activities: "Surfing, Hiking, Wildlife exploration",
    trip_name: "Surf trip in Sydney",
    isPublic: true,
    isSaved: false,
  },
];
